[2024-08-16T07:05:26.305+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-16T07:05:26.313+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2024-08-16T06:56:01.399983+00:00 [queued]>
[2024-08-16T07:05:26.318+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2024-08-16T06:56:01.399983+00:00 [queued]>
[2024-08-16T07:05:26.318+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-16T07:05:26.325+0000] {taskinstance.py:2879} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-08-16 06:56:01.399983+00:00
[2024-08-16T07:05:26.329+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T07:05:26.329+0000] {standard_task_runner.py:72} INFO - Started process 2123 to run task
[2024-08-16T07:05:26.330+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-08-16T06:56:01.399983+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpe89ya1gm']
[2024-08-16T07:05:26.331+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask is_api_available
[2024-08-16T07:05:26.356+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-08-16T06:56:01.399983+00:00 [running]> on host 891000986bfd
[2024-08-16T07:05:26.399+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T06:56:01.399983+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T06:56:01.399983+00:00'
[2024-08-16T07:05:26.400+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-16T07:05:26.400+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-16T07:05:26.401+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2024-08-16 07:05:26.314113+00:00
[2024-08-16T07:05:26.401+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2024-08-16T07:05:26.401+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-16T07:05:26.401+0000] {baseoperator.py:405} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-08-16T07:05:26.402+0000] {http.py:137} INFO - Poking: api/
[2024-08-16T07:05:26.406+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2024-08-16T07:05:26.748+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-08-16T07:05:26.761+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-16T07:05:26.762+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2024-08-16T06:56:01.399983+00:00, execution_date=20240816T065601, start_date=20240816T070526, end_date=20240816T070526
[2024-08-16T07:05:26.771+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-16T07:05:26.772+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-16T07:05:26.772+0000] {logging_mixin.py:190} INFO - Dag name:user_processing queued_at:2024-08-16 07:05:23.128804+00:00
[2024-08-16T07:05:26.772+0000] {logging_mixin.py:190} INFO - Task hostname:891000986bfd operator:HttpSensor
[2024-08-16T07:05:26.824+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-16T07:05:26.853+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T07:05:26.854+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
