[2024-08-17T00:30:16.605+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-17T00:30:16.611+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.store_user scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T00:30:16.615+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.store_user scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T00:30:16.615+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-17T00:30:16.619+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): store_user> on 2024-08-16 00:00:00+00:00
[2024-08-17T00:30:16.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=507) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T00:30:16.623+0000] {standard_task_runner.py:72} INFO - Started process 509 to run task
[2024-08-17T00:30:16.623+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwn1c2c_g']
[2024-08-17T00:30:16.624+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask store_user
[2024-08-17T00:30:16.643+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.store_user scheduled__2024-08-16T00:00:00+00:00 [running]> on host 83013fdeb55d
[2024-08-17T00:30:16.770+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='store_user' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-08-17T00:30:16.771+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-17T00:30:16.776+0000] {postgres.py:191} INFO - Running copy expert: COPY users FROM STDIN WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2024-08-17T00:30:16.780+0000] {base.py:84} INFO - Retrieving connection 'my_postgres'
[2024-08-17T00:30:16.782+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-17T00:30:16.786+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-17T00:30:16.786+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240817T003016, end_date=20240817T003016
[2024-08-17T00:30:16.813+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-17T00:30:16.819+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T00:30:16.820+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
