[2024-08-17T03:06:45.845+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-17T03:06:45.854+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_dag.branch scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T03:06:45.859+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_dag.branch scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T03:06:45.860+0000] {taskinstance.py:2856} INFO - Starting attempt 3 of 3
[2024-08-17T03:06:45.867+0000] {taskinstance.py:2879} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-08-16 00:00:00+00:00
[2024-08-17T03:06:45.870+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=428) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T03:06:45.871+0000] {standard_task_runner.py:72} INFO - Started process 429 to run task
[2024-08-17T03:06:45.872+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'branch', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpi50fqa18']
[2024-08-17T03:06:45.872+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask branch
[2024-08-17T03:06:45.898+0000] {task_command.py:467} INFO - Running <TaskInstance: xcom_dag.branch scheduled__2024-08-16T00:00:00+00:00 [running]> on host 0bd5af1ac055
[2024-08-17T03:06:45.938+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-08-17T03:06:45.939+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-17T03:06:45.948+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-17T03:06:45.954+0000] {python.py:240} INFO - Done. Returned value was: t2
[2024-08-17T03:06:45.955+0000] {branch.py:38} INFO - Branch into t2
[2024-08-17T03:06:45.955+0000] {skipmixin.py:230} INFO - Following branch ('t2',)
[2024-08-17T03:06:45.962+0000] {skipmixin.py:278} INFO - Skipping tasks [('t3', -1)]
[2024-08-17T03:06:45.976+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-17T03:06:45.976+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=branch, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240817T030645, end_date=20240817T030645
[2024-08-17T03:06:46.013+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-17T03:06:46.030+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T03:06:46.030+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
